name: CI Pipeline

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Run unit test
        run: ./mvnw clean test
